### ISSUE TITLE
Error generating template

### ISSUE THREAD

**Issue by rgomezcasas** [CodelyTV/scala-bootstrap-template.g8#11]
There is an error with the Travis File
![tmp 2018-11-21 11-39-09](https://user-images.githubusercontent.com/1331435/48836117-2362a980-ed82-11e8-99d1-a122e97130c0.png)

**Comment by JavierCane** [comment]
Fixed by https://github.com/CodelyTV/scala-bootstrap-template.g8/commit/1fbbd4ef87d401ce9236d8a28848b49dca8bde63
