### ISSUE TITLE
Creating a project with underscore in the name doesn't follow Scala file and class naming conventions

### ISSUE THREAD

**Issue by GMadorell** [CodelyTV/scala-bootstrap-template.g8#4]
Expected: when I create a project and put "poker_api" in the name, I expect a class named PokerApi.scala to be created

Actual: a class called Poker_api.scala is created instead (as can be seen in https://github.com/lambtors/poker-api/commit/6f623834752e06eef8f81bf9597a9b2d761ac6a4)

**Comment by JavierCane** [comment]
Hi @GMadorell!

The thing here is that you don't have to type the project name already in snake case. If you create a project with the name "Poker API", the template should convert it to snake case (`poker_api`) while creating the project folder, and to CamelCase (`PokerApi.scala`) while creating the main class 😬.

You can try it and, in case you find any unexpected behaviour, just reopen this issue.

Thanks a lot for the report!
